### ISSUE TITLE
Remove Bend (Req.ID 13)

### ISSUE THREAD

**Issue by manuele-lorusso** [Zeta-Project/yzeta#13]
Action:
Click on bend then "Entf" or Top Toolbar

Result:
Remove the Bend

Nice-to-have:
Remove bends with node --> Pull Node over edge and release. All bends which are not between the connected nodes will be deleted.

**Comment by dkoch2** [comment]
Das Nice-To-Have sollten wir als separates Issue anlegen mit niedriger Prio.

**Comment by dkoch2** [comment]
Edges können durch Entf oder die obere Toolbar entfernt werden.

"Nice to have" ist etwas komplexer durch die Eventsteuerung und Inputmodes des graphs.
