### ISSUE TITLE
Authentication at Zeta to get the concept definition

### ISSUE THREAD

**Issue by Markus396** [Zeta-Project/yzeta#34]
required for #31

**Comment by manuele-lorusso** [comment]
Actually the zeta authentication library "silhouttte" blocks cross-origin-requests and allow only same-origin. So it's impossible to make a REST Call from external yzeta.

Solution can be a configuration of zeta to allow CORS or we integrate yzeta concept editor into a zeta instance.

**Comment by manuele-lorusso** [comment]
zeta-dev.syslab server ist configured to allow CORS. Authentication is possibile, but without a good authentication endpoint it is not nice to call with zeta.

Also the integration into zeta is done, but to develop or test with all components of zeta is unefficient
